--CREATE TABLE [AppDbo].[Elimination] (
--    [ElimId]  INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
--	[ShortName] [varchar](50) NULL,
--	[Def] [varchar](50) NULL,
--	[ElimMapNbr] [varchar](5) NULL,
--	[ElimMapName] [varchar](50) NULL,
--	[ContractPrefix] [varchar](12) NULL,
--	[offsetBC] [varchar](2) NULL,
--	[offsetPC] [varchar](10) NULL,
--	[offsetPCdac] [varchar](10) NULL,
--	[forcePC] [varchar](10) NULL,
--	[forceTP] [varchar](5) NULL,
--	[UWyr] [varchar](1) NULL,
--	[StatLedger] [varchar](1) NULL,
--	[Notes] [varchar](100) NULL,
--	[TrueUpCo] [varchar](4) NULL,
--	[TrueUpAorC] [varchar](1) NULL,
--	[TrueUpMap] [varchar](5) NULL,
--	[TrueUpPC] [varchar](10) NULL,
--	[TrueUpBC] [varchar](2) NULL,
--	[TrueUpTP] [varchar](5) NULL,
--	[TrueUpContract] [varchar](15) NULL,
--	[DateTimeStamp] [datetime2](7)  NOT NULL DEFAULT (SYSUTCDATETIME()),
--)
--GO

--CREATE UNIQUE INDEX [IX_Elimination_ShortName] ON [AppDbo].[Elimination] ([ShortName]);
--GO
