--CREATE TABLE [dbo].[ElimSelect]
--(
--    [ElimSelectId] INT NOT NULL,
--	[ElimID] [int] NOT NULL,
--	[Pass] [int] NOT NULL,
--	[SubSeq] [int] NOT NULL,
--	[FieldName] [varchar](20) NULL,
--	[FieldNbr] [int] NOT NULL,
--	[IncExcl] [varchar](1) NULL,
--	[Oper] [varchar](2) NULL,
--	[FromVal] [varchar](255) NULL,
--	[ThruVal] [varchar](255) NULL,
--	[GLSU] [varchar](1) NULL,
--	[DateTimeStamp] [datetime2](7)  NOT NULL DEFAULT (SYSUTCDATETIME()),
--    [UserStamp]      NVARCHAR(50) NOT NULL DEFAULT (SUSER_SNAME())

--	CONSTRAINT [PK_ElimSelect] PRIMARY KEY CLUSTERED 
--	(
--		[ElimID] ASC,
--		[Pass] ASC,
--		[FieldNbr] ASC,
--		[SubSeq] ASC
--	)
--)
