create view [App].[PrincipalIdentity]
AS
    SELECT  x.[NameIdentifier]
            ,x.[UserName]
            ,x.[Email]
            ,x.[Disabled]
            ,x.[Role]
            ,x.[Parker]
            ,x.[ParkerPost]
			,x.[UserID_SAP]
			,x.[FirstName]
			,x.[NickName]
			,x.[MiddleName]
			,x.[LastName]
			,x.[Location]
			,x.[ParkPost]
			,x.[PostEmail]
			,x.[CCEmail1]
			,x.[CCEmail2]
			,x.[Elim]
			,x.[Co_Update]
			,x.[Co_View]
			,x.[CC_NodeID]
			,x.[Flex1]
			,x.[Flex2]
			,x.[Flex3]
			,x.[PostEmail2]

    FROM    [AppDbo].[PrincipalIdentity] x;